all:
  vars:
    ansible_user: alex
    ansible_python_interpreter: /usr/bin/python3

  children:
    k3s_master:
      hosts:
        master1:
          ansible_host: 172.20.70.150

    k3s_worker:
      hosts:
        worker1:
          ansible_host: 172.20.70.151

    jenkins_server:
      hosts:
        jenkins:
          ansible_host: 172.20.70.80
