apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-dashboards-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.20.70.150
    path: /srv/grafana-dashboards
  persistentVolumeReclaimPolicy: Retain
